# Makefile for all catalogs

CATCOMP= flexcat QUIET

all: DOpus4 DOpus4_Config DOpus4_Disk DOpus4_Icon DOpus4_Lib DOpus4_Print

DOpus4: DOpus4.cd deutsch/DOpus4.ct español/DOpus4.ct italiano/DOpus4.ct polski/DOpus4.ct \
suomi/DOpus4.ct èe¹tina/DOpus4.ct türkçe/DOpus4.ct català/DOpus4.ct français/DOpus4.ct
	-$(CATCOMP) $@.cd deutsch/$@.ct CATALOG LOCALE:Catalogs/deutsch/$@.catalog
	-$(CATCOMP) $@.cd español/$@.ct CATALOG LOCALE:Catalogs/español/$@.catalog
	-$(CATCOMP) $@.cd italiano/$@.ct CATALOG LOCALE:Catalogs/italiano/$@.catalog
	-$(CATCOMP) $@.cd polski/$@.ct CATALOG LOCALE:Catalogs/polski/$@.catalog
	-$(CATCOMP) $@.cd suomi/$@.ct CATALOG LOCALE:Catalogs/suomi/$@.catalog
	-$(CATCOMP) $@.cd èe¹tina/$@.ct CATALOG LOCALE:Catalogs/èe¹tina/$@.catalog
	-$(CATCOMP) $@.cd türkçe/$@.ct CATALOG LOCALE:Catalogs/türkçe/$@.catalog
	-$(CATCOMP) $@.cd català/$@.ct CATALOG LOCALE:Catalogs/català/$@.catalog
	-$(CATCOMP) $@.cd français/$@.ct CATALOG LOCALE:Catalogs/français/$@.catalog

DOpus4_Config: DOpus4_Config.cd deutsch/DOpus4_Config.ct español/DOpus4_Config.ct \
italiano/DOpus4_Config.ct polski/DOpus4_Config.ct suomi/DOpus4_Config.ct \
èe¹tina/DOpus4_Config.ct türkçe/DOpus4_Config.ct català/DOpus4_Config.ct français/DOpus4_Config.ct
	-$(CATCOMP) $@.cd deutsch/$@.ct CATALOG LOCALE:Catalogs/deutsch/$@.catalog
	-$(CATCOMP) $@.cd español/$@.ct CATALOG LOCALE:Catalogs/español/$@.catalog
	-$(CATCOMP) $@.cd italiano/$@.ct CATALOG LOCALE:Catalogs/italiano/$@.catalog
	-$(CATCOMP) $@.cd polski/$@.ct CATALOG LOCALE:Catalogs/polski/$@.catalog
	-$(CATCOMP) $@.cd suomi/$@.ct CATALOG LOCALE:Catalogs/suomi/$@.catalog
	-$(CATCOMP) $@.cd èe¹tina/$@.ct CATALOG LOCALE:Catalogs/èe¹tina/$@.catalog
	-$(CATCOMP) $@.cd türkçe/$@.ct CATALOG LOCALE:Catalogs/türkçe/$@.catalog
	-$(CATCOMP) $@.cd català/$@.ct CATALOG LOCALE:Catalogs/català/$@.catalog
	-$(CATCOMP) $@.cd français/$@.ct CATALOG LOCALE:Catalogs/français/$@.catalog

DOpus4_Disk: DOpus4.cd deutsch/DOpus4_Disk.ct español/DOpus4_Disk.ct italiano/DOpus4_Disk.ct \
polski/DOpus4_Disk.ct suomi/DOpus4_Disk.ct türkçe/DOpus4_Disk.ct català/DOpus4_Disk.ct \
français/DOpus4_Disk.ct #èe¹tina/DOpus4_Disk.ct
	-$(CATCOMP) $@.cd deutsch/$@.ct CATALOG LOCALE:Catalogs/deutsch/$@.catalog
	-$(CATCOMP) $@.cd español/$@.ct CATALOG LOCALE:Catalogs/español/$@.catalog
	-$(CATCOMP) $@.cd italiano/$@.ct CATALOG LOCALE:Catalogs/italiano/$@.catalog
	-$(CATCOMP) $@.cd polski/$@.ct CATALOG LOCALE:Catalogs/polski/$@.catalog
	-$(CATCOMP) $@.cd suomi/$@.ct CATALOG LOCALE:Catalogs/suomi/$@.catalog
#	-$(CATCOMP) $@.cd èe¹tina/$@.ct CATALOG LOCALE:Catalogs/èe¹tina/$@.catalog
	-$(CATCOMP) $@.cd türkçe/$@.ct CATALOG LOCALE:Catalogs/türkçe/$@.catalog
	-$(CATCOMP) $@.cd català/$@.ct CATALOG LOCALE:Catalogs/català/$@.catalog
	-$(CATCOMP) $@.cd français/$@.ct CATALOG LOCALE:Catalogs/français/$@.catalog

DOpus4_Icon: DOpus4_Icon.cd deutsch/DOpus4_Icon.ct español/DOpus4_Icon.ct italiano/DOpus4_Icon.ct \
polski/DOpus4_Icon.ct suomi/DOpus4_Icon.ct türkçe/DOpus4_Icon.ct català/DOpus4_Icon.ct \
français/DOpus4_Icon.ct #èe¹tina/DOpus4_Icon.ct
	-$(CATCOMP) $@.cd deutsch/$@.ct CATALOG LOCALE:Catalogs/deutsch/$@.catalog
	-$(CATCOMP) $@.cd español/$@.ct CATALOG LOCALE:Catalogs/español/$@.catalog
	-$(CATCOMP) $@.cd italiano/$@.ct CATALOG LOCALE:Catalogs/italiano/$@.catalog
	-$(CATCOMP) $@.cd polski/$@.ct CATALOG LOCALE:Catalogs/polski/$@.catalog
	-$(CATCOMP) $@.cd suomi/$@.ct CATALOG LOCALE:Catalogs/suomi/$@.catalog
#	-$(CATCOMP) $@.cd èe¹tina/$@.ct CATALOG LOCALE:Catalogs/èe¹tina/$@.catalog
	-$(CATCOMP) $@.cd türkçe/$@.ct CATALOG LOCALE:Catalogs/türkçe/$@.catalog
	-$(CATCOMP) $@.cd català/$@.ct CATALOG LOCALE:Catalogs/català/$@.catalog
	-$(CATCOMP) $@.cd français/$@.ct CATALOG LOCALE:Catalogs/français/$@.catalog

DOpus4_Lib: DOpus4_Lib.cd español/DOpus4_Lib.ct italiano/DOpus4_Lib.ct polski/DOpus4_Lib.ct \
èe¹tina/DOpus4_Lib.ct
#	-$(CATCOMP) $@.cd deutsch/$@.ct CATALOG LOCALE:Catalogs/deutsch/$@.catalog
	-$(CATCOMP) $@.cd español/$@.ct CATALOG LOCALE:Catalogs/español/$@.catalog
	-$(CATCOMP) $@.cd italiano/$@.ct CATALOG LOCALE:Catalogs/italiano/$@.catalog
	-$(CATCOMP) $@.cd polski/$@.ct CATALOG LOCALE:Catalogs/polski/$@.catalog
#	-$(CATCOMP) $@.cd suomi/$@.ct CATALOG LOCALE:Catalogs/suomi/$@.catalog
	-$(CATCOMP) $@.cd èe¹tina/$@.ct CATALOG LOCALE:Catalogs/èe¹tina/$@.catalog
#	-$(CATCOMP) $@.cd türkçe/$@.ct CATALOG LOCALE:Catalogs/türkçe/$@.catalog
#	-$(CATCOMP) $@.cd català/$@.ct CATALOG LOCALE:Catalogs/català/$@.catalog
#	-$(CATCOMP) $@.cd français/$@.ct CATALOG LOCALE:Catalogs/français/$@.catalog

DOpus4_Print: DOpus4_Print.cd deutsch/DOpus4_Print.ct español/DOpus4_Print.ct \
italiano/DOpus4_Print.ct polski/DOpus4_Print.ct suomi/DOpus4_Print.ct èe¹tina/DOpus4_Print.ct \
türkçe/DOpus4_Print.ct català/DOpus4_Print.ct français/DOpus4_Print.ct
	-$(CATCOMP) $@.cd deutsch/$@.ct CATALOG LOCALE:Catalogs/deutsch/$@.catalog
	-$(CATCOMP) $@.cd español/$@.ct CATALOG LOCALE:Catalogs/español/$@.catalog
	-$(CATCOMP) $@.cd italiano/$@.ct CATALOG LOCALE:Catalogs/italiano/$@.catalog
	-$(CATCOMP) $@.cd polski/$@.ct CATALOG LOCALE:Catalogs/polski/$@.catalog
	-$(CATCOMP) $@.cd suomi/$@.ct CATALOG LOCALE:Catalogs/suomi/$@.catalog
	-$(CATCOMP) $@.cd èe¹tina/$@.ct CATALOG LOCALE:Catalogs/èe¹tina/$@.catalog
	-$(CATCOMP) $@.cd türkçe/$@.ct CATALOG LOCALE:Catalogs/türkçe/$@.catalog
	-$(CATCOMP) $@.cd català/$@.ct CATALOG LOCALE:Catalogs/català/$@.catalog
	-$(CATCOMP) $@.cd français/$@.ct CATALOG LOCALE:Catalogs/français/$@.catalog


dist:
	lha -r a RAM:DOpus4Catalogs // LOCALE:Catalogs/DOpus4*
