void _DOpus_CreateGadgetBorders(struct DOpusRemember ** key, int w, int h, struct Border ** selborder, struct Border ** unselborder, int dogear, int shine, int shadow);
void _DOpus_HiliteGad(struct Gadget * gadget, struct RastPort * a1arg);
int _DOpus_AssignMenu(struct ConfigStuff * cstuff, int itemnum, char * name, char * func);
int _DOpus_AssignGadget(struct ConfigStuff * cstuff, int banknum, int gadnum, char * name, char * func);
int _DOpus_RefreshListView(struct DOpusListView * listview, int count);
void _DOpus_UScoreText(struct RastPort * rp, char * text, int x, int y, int upos);
int _DOpus_TackOn(char * path, char * name, int len);
void _DOpus_StrToUpper(char * from, char * to);
int _DOpus_StrToStamp(struct DateTime * datetime);
void _DOpus_StrToLower(char * from, char * to);
int _DOpus_StrConcat(char * s1, char * s2, int len);
int _DOpus_StrCombine(char * s1, char * s2, char * s3, int len);
void _DOpus_StampToStr(struct DateTime * datetime);
void _DOpus_ShowSlider(struct Window * window, struct Gadget * gadget);
void _DOpus_SetBusyPointer(struct Window * window);
void _DOpus_SelectGadget(struct Window * window, struct Gadget * gadget);
int _DOpus_SearchPathList(char * name, char * buffer, int size);
int _DOpus_SaveConfig(char * name, struct ConfigStuff * cstuff);
int _DOpus_RemoveListView(struct DOpusListView * listview, int count);
void _DOpus_RefreshStrGad(struct Gadget * gadget, struct Window * window);
void _DOpus_RefreshRequesterObject(struct RequesterBase * reqbase, struct RequesterObject * object);
int _DOpus_ReadStringFile(struct StringData * stringdata, char * filename);
int _DOpus_ReadConfig(STRPTR name, struct ConfigStuff * cstuff);
int _DOpus_RawkeyToStr(UWORD code, UWORD qual, char * buf, char * kbuf, int len);
int _DOpus_PathName(BPTR lock, char * buffer, int len);
struct Window *_DOpus_OpenRequester(struct RequesterBase * reqbase);
void _DOpus_ObjectText(struct RequesterBase * reqbase, short left, short top, short width, short height, char * text, unsigned short textpos);
void _DOpus_LStrnCpy(char * to, char * from, int len);
int _DOpus_LStrnCmpI(char * s1, char * s2, int len);
int _DOpus_LStrnCmp(char * s1, char * s2, int len);
void _DOpus_LStrnCat(char * s1, char * s2, int len);
void _DOpus_LStrCpy(char * to, char * from);
int _DOpus_LStrCmpI(char * s1, char * s2);
int _DOpus_LStrCmp(char * s1, char * s2);
void _DOpus_LStrCat(char * s1, char * s2);
struct DOpusListView *_DOpus_ListViewIDCMP(struct DOpusListView * listview, struct IntuiMessage * imsg);
void _DOpus_LFreeRemEntry(struct DOpusRemember ** key, char * pointer);
void _DOpus_LFreeRemember(struct DOpusRemember ** key);
void *_DOpus_LAllocRemember(struct DOpusRemember ** key, ULONG size, ULONG type);
void _DOpus_GhostGadget(struct Gadget * gad, struct RastPort * rp, int xoff, int yoff);
void _DOpus_GetWBScreen(struct Screen * scrbuf);
int _DOpus_GetSliderPos(struct Gadget * gadget, int count, int lines);
int _DOpus_GetDevices(struct ConfigStuff * cstuff);
struct Image *_DOpus_GetCheckImage(UBYTE fg, UBYTE bg, int pen, struct DOpusRemember ** key);
struct Image *_DOpus_GetButtonImage(int w, int h, int fg, int bg, int fpen, int bpen, struct DOpusRemember ** key);
int _DOpus_FSSetMenuStrip(struct Window * window, struct Menu * menu);
int _DOpus_FreeStringFile(struct StringData * stringdata);
int _DOpus_FreeConfig(struct ConfigStuff * cstuff);
void _DOpus_FixSliderPot(struct Window * window, struct Gadget * gadget, int offset, int count, int lines, int show);
void _DOpus_FixSliderBody(struct Window * window, struct Gadget * gadget, int count, int lines, int show);
int _DOpus_FindSystemFile(char * name, char * buffer, int size, int type);
int _DOpus_FileRequest(struct DOpusFileReq * freq);
void _DOpus_EnableGadget(struct Gadget * gad, struct RastPort * rp, int xoff, int yoff);
void _DOpus_DrawRadioButton(struct RastPort * rp, int x, int y, int w, int h, int hi, int lo);
void _DOpus_DrawCheckMark(struct RastPort * rp, int x, int y, int clear);
int _DOpus_DoSimpleRequest(struct Window * window, struct DOpusSimpleRequest * simplereq);
int _DOpus_DoRMBGadget(struct RMBGadget * rmbgadget, struct Window * window);
void _DOpus_DoGlassImage(struct RastPort * rp, struct Gadget * gadget, int shine, int shadow, int type);
void _DOpus_DoCycleGadget(struct Gadget * gadget, struct Window * window, char ** choices, int selection);
void _DOpus_DoArrow(struct RastPort * rp, int x, int y, int w, int h, int fg, int bg, int dir);
void _DOpus_Do3DStringBox(struct RastPort * rp, int x, int y, int w, int h, int tp, int bp);
void _DOpus_Do3DCycleBox(struct RastPort * rp, int x, int y, int w, int h, int tp, int bp);
void _DOpus_Do3DBox(struct RastPort * rp, int x, int y, int w, int h, int tp, int bp);
void _DOpus_DisableGadget(struct Gadget * gad, struct RastPort * rp, int xoff, int yoff);
int _DOpus_DefaultConfig(struct ConfigStuff * cstuff);
void _DOpus_Decode_RLE(char * source, char * dest, int size);
void _DOpus_CloseRequester(struct RequesterBase * reqbase);
int _DOpus_CheckNumGad(struct Gadget * gadget, struct Window * window, int min, int max);
int _DOpus_CheckHexGad(struct Gadget * gadget, struct Window * window, int min, int max);
int _DOpus_CheckExist(char * name, int * size);
int _DOpus_CheckConfig(struct ConfigStuff * cstuff);
void _DOpus_Do3DFrame(struct RastPort * a0arg, int x, int y, int w, int h, char * title, int tp, int bp);
int _DOpus_Atoh(char * str, int len);
int _DOpus_Assign(char * name, char * dir);
APTR _DOpus_AddRequesterObject(struct RequesterBase * reqbase, struct TagItem * taglist);
int _DOpus_AddListView(struct DOpusListView * listview, int count);
int _DOpus_AddGadgets(struct Window * window, struct Gadget * gadget, char ** text, int count, int fg, int bg, int add);
void _DOpus_AddGadgetBorders(struct DOpusRemember ** key, struct Gadget * gadget, int count, int shine, int shadow);
void _DOpus_ActivateStrGad(struct Gadget * gadget, struct Window * window);

